# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'uis/CameraSettings.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_CameraSettings(object):
    def setupUi(self, CameraSettings):
        CameraSettings.setObjectName("CameraSettings")
        CameraSettings.resize(842, 612)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(CameraSettings)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(CameraSettings)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.cmb_camera_type = QtWidgets.QComboBox(CameraSettings)
        self.cmb_camera_type.setStatusTip("")
        self.cmb_camera_type.setWhatsThis("")
        self.cmb_camera_type.setObjectName("cmb_camera_type")
        self.horizontalLayout.addWidget(self.cmb_camera_type)
        self.label_12 = QtWidgets.QLabel(CameraSettings)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout.addWidget(self.label_12)
        self.le_name = QtWidgets.QLineEdit(CameraSettings)
        self.le_name.setStatusTip("")
        self.le_name.setWhatsThis("")
        self.le_name.setObjectName("le_name")
        self.horizontalLayout.addWidget(self.le_name)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.chk_enabled = QtWidgets.QCheckBox(CameraSettings)
        self.chk_enabled.setChecked(True)
        self.chk_enabled.setObjectName("chk_enabled")
        self.horizontalLayout.addWidget(self.chk_enabled)
        self.cmd_delete = QtWidgets.QPushButton(CameraSettings)
        self.cmd_delete.setObjectName("cmd_delete")
        self.horizontalLayout.addWidget(self.cmd_delete)
        self.verticalLayout_5.addLayout(self.horizontalLayout)
        self.fr_tango = QtWidgets.QFrame(CameraSettings)
        self.fr_tango.setObjectName("fr_tango")
        self.gridLayout = QtWidgets.QGridLayout(self.fr_tango)
        self.gridLayout.setObjectName("gridLayout")
        self.chk_manual_tango_device = QtWidgets.QCheckBox(self.fr_tango)
        self.chk_manual_tango_device.setObjectName("chk_manual_tango_device")
        self.gridLayout.addWidget(self.chk_manual_tango_device, 1, 3, 1, 1)
        self.cmd_rescan_database = QtWidgets.QPushButton(self.fr_tango)
        self.cmd_rescan_database.setObjectName("cmd_rescan_database")
        self.gridLayout.addWidget(self.cmd_rescan_database, 0, 3, 1, 1)
        self.cmb_tango_device = QtWidgets.QComboBox(self.fr_tango)
        self.cmb_tango_device.setObjectName("cmb_tango_device")
        self.gridLayout.addWidget(self.cmb_tango_device, 1, 2, 1, 1)
        self.le_tango_host = QtWidgets.QLineEdit(self.fr_tango)
        self.le_tango_host.setObjectName("le_tango_host")
        self.gridLayout.addWidget(self.le_tango_host, 0, 2, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.fr_tango)
        self.label_13.setObjectName("label_13")
        self.gridLayout.addWidget(self.label_13, 0, 0, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.fr_tango)
        self.label_14.setObjectName("label_14")
        self.gridLayout.addWidget(self.label_14, 1, 0, 1, 1)
        self.le_tango_server = QtWidgets.QLineEdit(self.fr_tango)
        self.le_tango_server.setEnabled(False)
        self.le_tango_server.setStatusTip("")
        self.le_tango_server.setWhatsThis("")
        self.le_tango_server.setObjectName("le_tango_server")
        self.gridLayout.addWidget(self.le_tango_server, 1, 4, 1, 1)
        self.cmb_roi_device = QtWidgets.QComboBox(self.fr_tango)
        self.cmb_roi_device.setObjectName("cmb_roi_device")
        self.gridLayout.addWidget(self.cmb_roi_device, 2, 2, 1, 1)
        self.le_roi_server = QtWidgets.QLineEdit(self.fr_tango)
        self.le_roi_server.setEnabled(False)
        self.le_roi_server.setStatusTip("")
        self.le_roi_server.setWhatsThis("")
        self.le_roi_server.setObjectName("le_roi_server")
        self.gridLayout.addWidget(self.le_roi_server, 2, 4, 1, 1)
        self.chk_manual_roi_device = QtWidgets.QCheckBox(self.fr_tango)
        self.chk_manual_roi_device.setObjectName("chk_manual_roi_device")
        self.gridLayout.addWidget(self.chk_manual_roi_device, 2, 3, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 1, 5, 1, 1)
        self.chk_roi_server = QtWidgets.QCheckBox(self.fr_tango)
        self.chk_roi_server.setObjectName("chk_roi_server")
        self.gridLayout.addWidget(self.chk_roi_server, 2, 0, 1, 1)
        self.verticalLayout_5.addWidget(self.fr_tango)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_5 = QtWidgets.QLabel(CameraSettings)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_2.addWidget(self.label_5)
        self.cmb_motor_type = QtWidgets.QComboBox(CameraSettings)
        self.cmb_motor_type.setObjectName("cmb_motor_type")
        self.horizontalLayout_2.addWidget(self.cmb_motor_type)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.verticalLayout_5.addLayout(self.horizontalLayout_2)
        self.fr_motor = QtWidgets.QFrame(CameraSettings)
        self.fr_motor.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fr_motor.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fr_motor.setObjectName("fr_motor")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.fr_motor)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.fr_fsbt = QtWidgets.QFrame(self.fr_motor)
        self.fr_fsbt.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fr_fsbt.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fr_fsbt.setObjectName("fr_fsbt")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.fr_fsbt)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_7 = QtWidgets.QLabel(self.fr_fsbt)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_7.addWidget(self.label_7)
        self.le_fsbt_host = QtWidgets.QLineEdit(self.fr_fsbt)
        self.le_fsbt_host.setObjectName("le_fsbt_host")
        self.horizontalLayout_7.addWidget(self.le_fsbt_host)
        self.verticalLayout_2.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_8 = QtWidgets.QLabel(self.fr_fsbt)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_8.addWidget(self.label_8)
        self.le_fsbt_port = QtWidgets.QLineEdit(self.fr_fsbt)
        self.le_fsbt_port.setObjectName("le_fsbt_port")
        self.horizontalLayout_8.addWidget(self.le_fsbt_port)
        self.verticalLayout_2.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_9 = QtWidgets.QLabel(self.fr_fsbt)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_9.addWidget(self.label_9)
        self.le_fsbt_motor_name = QtWidgets.QLineEdit(self.fr_fsbt)
        self.le_fsbt_motor_name.setObjectName("le_fsbt_motor_name")
        self.horizontalLayout_9.addWidget(self.le_fsbt_motor_name)
        self.verticalLayout_2.addLayout(self.horizontalLayout_9)
        self.verticalLayout_4.addWidget(self.fr_fsbt)
        self.fr_acromag = QtWidgets.QFrame(self.fr_motor)
        self.fr_acromag.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fr_acromag.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fr_acromag.setObjectName("fr_acromag")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.fr_acromag)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_10 = QtWidgets.QLabel(self.fr_acromag)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_10.addWidget(self.label_10)
        self.le_acromag_server = QtWidgets.QLineEdit(self.fr_acromag)
        self.le_acromag_server.setObjectName("le_acromag_server")
        self.horizontalLayout_10.addWidget(self.le_acromag_server)
        self.verticalLayout_3.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_11 = QtWidgets.QLabel(self.fr_acromag)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_11.addWidget(self.label_11)
        self.le_acromag_valve = QtWidgets.QLineEdit(self.fr_acromag)
        self.le_acromag_valve.setObjectName("le_acromag_valve")
        self.horizontalLayout_11.addWidget(self.le_acromag_valve)
        self.verticalLayout_3.addLayout(self.horizontalLayout_11)
        self.verticalLayout_4.addWidget(self.fr_acromag)
        self.verticalLayout_5.addWidget(self.fr_motor)
        self.gb_status_source = QtWidgets.QGroupBox(CameraSettings)
        self.gb_status_source.setObjectName("gb_status_source")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.gb_status_source)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.but_status_source_tango = QtWidgets.QRadioButton(self.gb_status_source)
        self.but_status_source_tango.setChecked(True)
        self.but_status_source_tango.setObjectName("but_status_source_tango")
        self.bg_status_source = QtWidgets.QButtonGroup(CameraSettings)
        self.bg_status_source.setObjectName("bg_status_source")
        self.bg_status_source.addButton(self.but_status_source_tango)
        self.gridLayout_3.addWidget(self.but_status_source_tango, 0, 0, 1, 1)
        self.but_status_source_infoscreen = QtWidgets.QRadioButton(self.gb_status_source)
        self.but_status_source_infoscreen.setObjectName("but_status_source_infoscreen")
        self.bg_status_source.addButton(self.but_status_source_infoscreen)
        self.gridLayout_3.addWidget(self.but_status_source_infoscreen, 1, 0, 1, 1)
        self.le_status_server = QtWidgets.QLineEdit(self.gb_status_source)
        self.le_status_server.setObjectName("le_status_server")
        self.gridLayout_3.addWidget(self.le_status_server, 0, 1, 1, 1)
        self.cmd_default_status_source = QtWidgets.QPushButton(self.gb_status_source)
        self.cmd_default_status_source.setObjectName("cmd_default_status_source")
        self.gridLayout_3.addWidget(self.cmd_default_status_source, 0, 2, 1, 1)
        self.verticalLayout_5.addWidget(self.gb_status_source)
        self.groupBox = QtWidgets.QGroupBox(CameraSettings)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.chk_flip_v = QtWidgets.QCheckBox(self.groupBox)
        self.chk_flip_v.setObjectName("chk_flip_v")
        self.gridLayout_2.addWidget(self.chk_flip_v, 0, 0, 1, 1)
        self.chk_flip_h = QtWidgets.QCheckBox(self.groupBox)
        self.chk_flip_h.setObjectName("chk_flip_h")
        self.gridLayout_2.addWidget(self.chk_flip_h, 3, 0, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_3.addWidget(self.label_6)
        self.sp_rotate = QtWidgets.QSpinBox(self.groupBox)
        self.sp_rotate.setMaximum(3)
        self.sp_rotate.setObjectName("sp_rotate")
        self.horizontalLayout_3.addWidget(self.sp_rotate)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem3)
        self.gridLayout_2.addLayout(self.horizontalLayout_3, 4, 0, 1, 2)
        self.chk_color = QtWidgets.QCheckBox(self.groupBox)
        self.chk_color.setObjectName("chk_color")
        self.gridLayout_2.addWidget(self.chk_color, 0, 1, 1, 1)
        self.chk_high_depth = QtWidgets.QCheckBox(self.groupBox)
        self.chk_high_depth.setObjectName("chk_high_depth")
        self.gridLayout_2.addWidget(self.chk_high_depth, 3, 1, 1, 1)
        self.verticalLayout_5.addWidget(self.groupBox)
        spacerItem4 = QtWidgets.QSpacerItem(20, 70, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem4)

        self.retranslateUi(CameraSettings)
        QtCore.QMetaObject.connectSlotsByName(CameraSettings)

    def retranslateUi(self, CameraSettings):
        _translate = QtCore.QCoreApplication.translate
        CameraSettings.setWindowTitle(_translate("CameraSettings", "CameraSettings"))
        self.label.setText(_translate("CameraSettings", "Camera type"))
        self.cmb_camera_type.setToolTip(_translate("CameraSettings", "Select camera type"))
        self.label_12.setText(_translate("CameraSettings", "Displayed name:"))
        self.le_name.setToolTip(_translate("CameraSettings", "Under this name camera will be displayed in viewer"))
        self.chk_enabled.setText(_translate("CameraSettings", "Enabled"))
        self.cmd_delete.setText(_translate("CameraSettings", "Delete"))
        self.chk_manual_tango_device.setText(_translate("CameraSettings", "Specify manually:"))
        self.cmd_rescan_database.setText(_translate("CameraSettings", "Rescan database"))
        self.le_tango_host.setToolTip(_translate("CameraSettings", "Type tango database host, e.g. hasep23oh"))
        self.label_13.setText(_translate("CameraSettings", "TangoDB host:"))
        self.label_14.setText(_translate("CameraSettings", "Select camera:"))
        self.le_tango_server.setToolTip(_translate("CameraSettings", "Camera tango device, e.g. pXX/lmscreen/LM_XX"))
        self.le_roi_server.setToolTip(_translate("CameraSettings", "Camera tango device, e.g. pXX/lmscreen/LM_XX"))
        self.chk_manual_roi_device.setText(_translate("CameraSettings", "Specify manually:"))
        self.chk_roi_server.setText(_translate("CameraSettings", "ROI server"))
        self.label_5.setText(_translate("CameraSettings", "Screen motor type"))
        self.cmb_motor_type.setWhatsThis(_translate("CameraSettings", "If screen has a tango motor"))
        self.label_7.setText(_translate("CameraSettings", "FSBT server host"))
        self.label_8.setText(_translate("CameraSettings", "FSBT server post"))
        self.label_9.setText(_translate("CameraSettings", "FSBT motor name"))
        self.label_10.setText(_translate("CameraSettings", "Valve tango server"))
        self.label_11.setText(_translate("CameraSettings", "Valve channel"))
        self.gb_status_source.setTitle(_translate("CameraSettings", "Status screen source"))
        self.but_status_source_tango.setText(_translate("CameraSettings", "General tango server (refresh ~3 sec)"))
        self.but_status_source_infoscreen.setText(_translate("CameraSettings", "800x600 infoscreen (refresh ~90 sec) "))
        self.cmd_default_status_source.setText(_translate("CameraSettings", "Set to default"))
        self.groupBox.setTitle(_translate("CameraSettings", "Picture settings"))
        self.chk_flip_v.setText(_translate("CameraSettings", "Flip vertical"))
        self.chk_flip_h.setText(_translate("CameraSettings", "Flip horizontal"))
        self.label_6.setText(_translate("CameraSettings", "Rotate in 90 deg step"))
        self.chk_color.setText(_translate("CameraSettings", "Color"))
        self.chk_high_depth.setText(_translate("CameraSettings", "High depth"))

