# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'uis/LogWidget.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_LogWidget(object):
    def setupUi(self, LogWidget):
        LogWidget.setObjectName("LogWidget")
        LogWidget.resize(561, 410)
        self.horizontalLayout = QtWidgets.QHBoxLayout(LogWidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.teLogs = QtWidgets.QPlainTextEdit(LogWidget)
        self.teLogs.setReadOnly(True)
        self.teLogs.setObjectName("teLogs")
        self.horizontalLayout.addWidget(self.teLogs)

        self.retranslateUi(LogWidget)
        QtCore.QMetaObject.connectSlotsByName(LogWidget)

    def retranslateUi(self, LogWidget):
        _translate = QtCore.QCoreApplication.translate
        LogWidget.setWindowTitle(_translate("LogWidget", "Form"))
