# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/SettingsWidget.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SettingsWidget(object):
    def setupUi(self, SettingsWidget):
        SettingsWidget.setObjectName("SettingsWidget")
        SettingsWidget.resize(457, 847)
        SettingsWidget.setMinimumSize(QtCore.QSize(0, 0))
        SettingsWidget.setMaximumSize(QtCore.QSize(457, 16777215))
        self.verticalLayout = QtWidgets.QVBoxLayout(SettingsWidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(SettingsWidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.groupBox = QtWidgets.QGroupBox(self.tab)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame_Source = QtWidgets.QFrame(self.groupBox)
        self.frame_Source.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_Source.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_Source.setObjectName("frame_Source")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame_Source)
        self.horizontalLayout_5.setContentsMargins(3, 3, 3, 3)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_26 = QtWidgets.QLabel(self.frame_Source)
        self.label_26.setMinimumSize(QtCore.QSize(125, 0))
        self.label_26.setObjectName("label_26")
        self.horizontalLayout_5.addWidget(self.label_26)
        self.cmb_source = QtWidgets.QComboBox(self.frame_Source)
        self.cmb_source.setMinimumSize(QtCore.QSize(200, 0))
        self.cmb_source.setObjectName("cmb_source")
        self.horizontalLayout_5.addWidget(self.cmb_source)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem)
        self.verticalLayout_3.addWidget(self.frame_Source)
        self.frame_Folder = QtWidgets.QFrame(self.groupBox)
        self.frame_Folder.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_Folder.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_Folder.setObjectName("frame_Folder")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_Folder)
        self.horizontalLayout_4.setContentsMargins(3, 3, 3, 3)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_23 = QtWidgets.QLabel(self.frame_Folder)
        self.label_23.setMinimumSize(QtCore.QSize(125, 0))
        self.label_23.setObjectName("label_23")
        self.horizontalLayout_4.addWidget(self.label_23)
        self.cmb_Path = QtWidgets.QComboBox(self.frame_Folder)
        self.cmb_Path.setMinimumSize(QtCore.QSize(200, 0))
        self.cmb_Path.setObjectName("cmb_Path")
        self.horizontalLayout_4.addWidget(self.cmb_Path)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.verticalLayout_3.addWidget(self.frame_Folder)
        self.frame_Exposure = QtWidgets.QFrame(self.groupBox)
        self.frame_Exposure.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_Exposure.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_Exposure.setObjectName("frame_Exposure")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frame_Exposure)
        self.horizontalLayout_6.setContentsMargins(3, 3, 3, 3)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label = QtWidgets.QLabel(self.frame_Exposure)
        self.label.setMinimumSize(QtCore.QSize(125, 0))
        self.label.setObjectName("label")
        self.horizontalLayout_6.addWidget(self.label)
        self.sbExposureTime = QtWidgets.QSpinBox(self.frame_Exposure)
        self.sbExposureTime.setMinimumSize(QtCore.QSize(75, 0))
        self.sbExposureTime.setMaximumSize(QtCore.QSize(75, 16777215))
        self.sbExposureTime.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.sbExposureTime.setMinimum(50)
        self.sbExposureTime.setMaximum(1000000)
        self.sbExposureTime.setObjectName("sbExposureTime")
        self.horizontalLayout_6.addWidget(self.sbExposureTime)
        self.label_3 = QtWidgets.QLabel(self.frame_Exposure)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_6.addWidget(self.label_3)
        self.sbGain = QtWidgets.QSpinBox(self.frame_Exposure)
        self.sbGain.setMinimumSize(QtCore.QSize(75, 0))
        self.sbGain.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.sbGain.setMaximum(22)
        self.sbGain.setObjectName("sbGain")
        self.horizontalLayout_6.addWidget(self.sbGain)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem2)
        self.verticalLayout_3.addWidget(self.frame_Exposure)
        self.frame_Cut = QtWidgets.QFrame(self.groupBox)
        self.frame_Cut.setObjectName("frame_Cut")
        self.gridLayout = QtWidgets.QGridLayout(self.frame_Cut)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem3, 0, 5, 1, 1)
        self.sbViewH = QtWidgets.QSpinBox(self.frame_Cut)
        self.sbViewH.setMinimum(4)
        self.sbViewH.setMaximum(9999)
        self.sbViewH.setSingleStep(4)
        self.sbViewH.setObjectName("sbViewH")
        self.gridLayout.addWidget(self.sbViewH, 1, 4, 1, 1)
        self.label_22 = QtWidgets.QLabel(self.frame_Cut)
        self.label_22.setMinimumSize(QtCore.QSize(100, 0))
        self.label_22.setObjectName("label_22")
        self.gridLayout.addWidget(self.label_22, 0, 0, 2, 1)
        self.sbViewW = QtWidgets.QSpinBox(self.frame_Cut)
        self.sbViewW.setMinimum(4)
        self.sbViewW.setMaximum(9999)
        self.sbViewW.setSingleStep(4)
        self.sbViewW.setObjectName("sbViewW")
        self.gridLayout.addWidget(self.sbViewW, 1, 2, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.frame_Cut)
        self.label_19.setMinimumSize(QtCore.QSize(20, 0))
        self.label_19.setObjectName("label_19")
        self.gridLayout.addWidget(self.label_19, 0, 1, 1, 1)
        self.sbViewY = QtWidgets.QSpinBox(self.frame_Cut)
        self.sbViewY.setMinimumSize(QtCore.QSize(75, 0))
        self.sbViewY.setMaximum(9999)
        self.sbViewY.setSingleStep(4)
        self.sbViewY.setObjectName("sbViewY")
        self.gridLayout.addWidget(self.sbViewY, 0, 4, 1, 1)
        self.label_28 = QtWidgets.QLabel(self.frame_Cut)
        self.label_28.setObjectName("label_28")
        self.gridLayout.addWidget(self.label_28, 1, 3, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.frame_Cut)
        self.label_20.setMinimumSize(QtCore.QSize(25, 0))
        self.label_20.setObjectName("label_20")
        self.gridLayout.addWidget(self.label_20, 0, 3, 1, 1)
        self.sbViewX = QtWidgets.QSpinBox(self.frame_Cut)
        self.sbViewX.setMinimumSize(QtCore.QSize(75, 0))
        self.sbViewX.setMaximum(9999)
        self.sbViewX.setSingleStep(4)
        self.sbViewX.setObjectName("sbViewX")
        self.gridLayout.addWidget(self.sbViewX, 0, 2, 1, 1)
        self.label_27 = QtWidgets.QLabel(self.frame_Cut)
        self.label_27.setObjectName("label_27")
        self.gridLayout.addWidget(self.label_27, 1, 1, 1, 1)
        self.verticalLayout_3.addWidget(self.frame_Cut)
        self.frame_Reduce = QtWidgets.QFrame(self.groupBox)
        self.frame_Reduce.setObjectName("frame_Reduce")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.frame_Reduce)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.lbFps_2 = QtWidgets.QLabel(self.frame_Reduce)
        self.lbFps_2.setMinimumSize(QtCore.QSize(125, 0))
        self.lbFps_2.setObjectName("lbFps_2")
        self.horizontalLayout_9.addWidget(self.lbFps_2)
        self.sbReduce = QtWidgets.QSpinBox(self.frame_Reduce)
        self.sbReduce.setMinimumSize(QtCore.QSize(75, 0))
        self.sbReduce.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.sbReduce.setMinimum(1)
        self.sbReduce.setObjectName("sbReduce")
        self.horizontalLayout_9.addWidget(self.sbReduce)
        self.lbFps_3 = QtWidgets.QLabel(self.frame_Reduce)
        self.lbFps_3.setObjectName("lbFps_3")
        self.horizontalLayout_9.addWidget(self.lbFps_3)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem4)
        self.verticalLayout_3.addWidget(self.frame_Reduce)
        self.frame_FPS = QtWidgets.QFrame(self.groupBox)
        self.frame_FPS.setObjectName("frame_FPS")
        self.layout_FPS = QtWidgets.QHBoxLayout(self.frame_FPS)
        self.layout_FPS.setObjectName("layout_FPS")
        self.lbFps = QtWidgets.QLabel(self.frame_FPS)
        self.lbFps.setMinimumSize(QtCore.QSize(125, 0))
        self.lbFps.setObjectName("lbFps")
        self.layout_FPS.addWidget(self.lbFps)
        self.sbFPS = QtWidgets.QSpinBox(self.frame_FPS)
        self.sbFPS.setMinimumSize(QtCore.QSize(75, 0))
        self.sbFPS.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.sbFPS.setMinimum(1)
        self.sbFPS.setObjectName("sbFPS")
        self.layout_FPS.addWidget(self.sbFPS)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.layout_FPS.addItem(spacerItem5)
        self.verticalLayout_3.addWidget(self.frame_FPS)
        self.frame_Dark_Image = QtWidgets.QFrame(self.groupBox)
        self.frame_Dark_Image.setObjectName("frame_Dark_Image")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame_Dark_Image)
        self.gridLayout_2.setContentsMargins(1, 1, 1, 1)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.chk_dark_image = QtWidgets.QCheckBox(self.frame_Dark_Image)
        self.chk_dark_image.setObjectName("chk_dark_image")
        self.gridLayout_2.addWidget(self.chk_dark_image, 0, 0, 1, 1)
        self.but_acq_dark_image = QtWidgets.QPushButton(self.frame_Dark_Image)
        self.but_acq_dark_image.setObjectName("but_acq_dark_image")
        self.gridLayout_2.addWidget(self.but_acq_dark_image, 1, 0, 1, 1)
        self.but_load_dark_image = QtWidgets.QPushButton(self.frame_Dark_Image)
        self.but_load_dark_image.setObjectName("but_load_dark_image")
        self.gridLayout_2.addWidget(self.but_load_dark_image, 1, 1, 1, 1)
        self.but_save_dark_image = QtWidgets.QPushButton(self.frame_Dark_Image)
        self.but_save_dark_image.setObjectName("but_save_dark_image")
        self.gridLayout_2.addWidget(self.but_save_dark_image, 1, 2, 1, 1)
        self.verticalLayout_3.addWidget(self.frame_Dark_Image)
        self.tbAllParams = QtWidgets.QPushButton(self.groupBox)
        self.tbAllParams.setObjectName("tbAllParams")
        self.verticalLayout_3.addWidget(self.tbAllParams)
        self.verticalLayout_5.addWidget(self.groupBox)
        self.groupBox_4 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_4.setObjectName("groupBox_4")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.chkAutoLevels = QtWidgets.QCheckBox(self.groupBox_4)
        self.chkAutoLevels.setChecked(True)
        self.chkAutoLevels.setObjectName("chkAutoLevels")
        self.verticalLayout_7.addWidget(self.chkAutoLevels)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_2 = QtWidgets.QLabel(self.groupBox_4)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_11.addWidget(self.label_2)
        self.sbMinLevel = QtWidgets.QDoubleSpinBox(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sbMinLevel.sizePolicy().hasHeightForWidth())
        self.sbMinLevel.setSizePolicy(sizePolicy)
        self.sbMinLevel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.sbMinLevel.setMaximum(300.0)
        self.sbMinLevel.setObjectName("sbMinLevel")
        self.horizontalLayout_11.addWidget(self.sbMinLevel)
        self.label_4 = QtWidgets.QLabel(self.groupBox_4)
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_11.addWidget(self.label_4)
        self.sbMaxLevel = QtWidgets.QDoubleSpinBox(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sbMaxLevel.sizePolicy().hasHeightForWidth())
        self.sbMaxLevel.setSizePolicy(sizePolicy)
        self.sbMaxLevel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.sbMaxLevel.setMaximum(300.0)
        self.sbMaxLevel.setProperty("value", 1.0)
        self.sbMaxLevel.setObjectName("sbMaxLevel")
        self.horizontalLayout_11.addWidget(self.sbMaxLevel)
        self.verticalLayout_7.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_5 = QtWidgets.QLabel(self.groupBox_4)
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_12.addWidget(self.label_5)
        self.cbColorMap = QtWidgets.QComboBox(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cbColorMap.sizePolicy().hasHeightForWidth())
        self.cbColorMap.setSizePolicy(sizePolicy)
        self.cbColorMap.setMinimumSize(QtCore.QSize(0, 0))
        self.cbColorMap.setObjectName("cbColorMap")
        self.cbColorMap.addItem("")
        self.cbColorMap.addItem("")
        self.cbColorMap.addItem("")
        self.cbColorMap.addItem("")
        self.cbColorMap.addItem("")
        self.cbColorMap.addItem("")
        self.cbColorMap.addItem("")
        self.cbColorMap.addItem("")
        self.horizontalLayout_12.addWidget(self.cbColorMap)
        self.verticalLayout_7.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.rb_lin_level = QtWidgets.QRadioButton(self.groupBox_4)
        self.rb_lin_level.setChecked(True)
        self.rb_lin_level.setObjectName("rb_lin_level")
        self.bg_level = QtWidgets.QButtonGroup(SettingsWidget)
        self.bg_level.setObjectName("bg_level")
        self.bg_level.addButton(self.rb_lin_level)
        self.horizontalLayout_13.addWidget(self.rb_lin_level)
        self.rb_log_level = QtWidgets.QRadioButton(self.groupBox_4)
        self.rb_log_level.setObjectName("rb_log_level")
        self.bg_level.addButton(self.rb_log_level)
        self.horizontalLayout_13.addWidget(self.rb_log_level)
        self.rb_sqrt_level = QtWidgets.QRadioButton(self.groupBox_4)
        self.rb_sqrt_level.setObjectName("rb_sqrt_level")
        self.bg_level.addButton(self.rb_sqrt_level)
        self.horizontalLayout_13.addWidget(self.rb_sqrt_level)
        self.verticalLayout_7.addLayout(self.horizontalLayout_13)
        self.verticalLayout_5.addWidget(self.groupBox_4)
        self.gb_screen_motor = QtWidgets.QGroupBox(self.tab)
        self.gb_screen_motor.setObjectName("gb_screen_motor")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.gb_screen_motor)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lb_screen_status = QtWidgets.QLabel(self.gb_screen_motor)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lb_screen_status.setFont(font)
        self.lb_screen_status.setObjectName("lb_screen_status")
        self.horizontalLayout_2.addWidget(self.lb_screen_status)
        self.pbInOut = QtWidgets.QPushButton(self.gb_screen_motor)
        self.pbInOut.setMinimumSize(QtCore.QSize(50, 0))
        self.pbInOut.setObjectName("pbInOut")
        self.horizontalLayout_2.addWidget(self.pbInOut)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem6)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem7)
        self.chk_auto_screen = QtWidgets.QCheckBox(self.gb_screen_motor)
        self.chk_auto_screen.setObjectName("chk_auto_screen")
        self.horizontalLayout_2.addWidget(self.chk_auto_screen)
        self.verticalLayout_5.addWidget(self.gb_screen_motor)
        self.gb_sardana = QtWidgets.QGroupBox(self.tab)
        self.gb_sardana.setObjectName("gb_sardana")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.gb_sardana)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.lb_screen_status_2 = QtWidgets.QLabel(self.gb_sardana)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.lb_screen_status_2.setFont(font)
        self.lb_screen_status_2.setObjectName("lb_screen_status_2")
        self.horizontalLayout_3.addWidget(self.lb_screen_status_2)
        self.cb_counter = QtWidgets.QComboBox(self.gb_sardana)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cb_counter.sizePolicy().hasHeightForWidth())
        self.cb_counter.setSizePolicy(sizePolicy)
        self.cb_counter.setMinimumSize(QtCore.QSize(0, 0))
        self.cb_counter.setObjectName("cb_counter")
        self.cb_counter.addItem("")
        self.cb_counter.addItem("")
        self.cb_counter.addItem("")
        self.cb_counter.addItem("")
        self.cb_counter.addItem("")
        self.cb_counter.addItem("")
        self.cb_counter.addItem("")
        self.cb_counter.addItem("")
        self.horizontalLayout_3.addWidget(self.cb_counter)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem8)
        self.verticalLayout_5.addWidget(self.gb_sardana)
        spacerItem9 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem9)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.tab_2)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem10)
        self.but_add_marker = QtWidgets.QPushButton(self.groupBox_2)
        self.but_add_marker.setObjectName("but_add_marker")
        self.horizontalLayout.addWidget(self.but_add_marker)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.layout_markers = QtWidgets.QWidget(self.groupBox_2)
        self.layout_markers.setMinimumSize(QtCore.QSize(0, 0))
        self.layout_markers.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.layout_markers.setObjectName("layout_markers")
        self.verticalLayout_2.addWidget(self.layout_markers)
        self.verticalLayout_4.addWidget(self.groupBox_2)
        self.groupBox_3 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.sbRoiY = QtWidgets.QSpinBox(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sbRoiY.sizePolicy().hasHeightForWidth())
        self.sbRoiY.setSizePolicy(sizePolicy)
        self.sbRoiY.setMaximum(9999)
        self.sbRoiY.setObjectName("sbRoiY")
        self.gridLayout_3.addWidget(self.sbRoiY, 2, 3, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.groupBox_3)
        self.label_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName("label_6")
        self.gridLayout_3.addWidget(self.label_6, 2, 0, 1, 1)
        self.chbShowRoi = QtWidgets.QCheckBox(self.groupBox_3)
        self.chbShowRoi.setObjectName("chbShowRoi")
        self.gridLayout_3.addWidget(self.chbShowRoi, 0, 0, 1, 1)
        self.sbRoiX = QtWidgets.QSpinBox(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sbRoiX.sizePolicy().hasHeightForWidth())
        self.sbRoiX.setSizePolicy(sizePolicy)
        self.sbRoiX.setMaximum(9999)
        self.sbRoiX.setObjectName("sbRoiX")
        self.gridLayout_3.addWidget(self.sbRoiX, 2, 1, 1, 1)
        self.sbRoiHeight = QtWidgets.QSpinBox(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sbRoiHeight.sizePolicy().hasHeightForWidth())
        self.sbRoiHeight.setSizePolicy(sizePolicy)
        self.sbRoiHeight.setMaximum(9999)
        self.sbRoiHeight.setObjectName("sbRoiHeight")
        self.gridLayout_3.addWidget(self.sbRoiHeight, 3, 3, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.groupBox_3)
        self.label_8.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_8.setObjectName("label_8")
        self.gridLayout_3.addWidget(self.label_8, 3, 2, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.groupBox_3)
        self.label_9.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_9.setObjectName("label_9")
        self.gridLayout_3.addWidget(self.label_9, 3, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.groupBox_3)
        self.label_7.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName("label_7")
        self.gridLayout_3.addWidget(self.label_7, 2, 2, 1, 1)
        self.sbRoiWidth = QtWidgets.QSpinBox(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sbRoiWidth.sizePolicy().hasHeightForWidth())
        self.sbRoiWidth.setSizePolicy(sizePolicy)
        self.sbRoiWidth.setMaximum(9999)
        self.sbRoiWidth.setObjectName("sbRoiWidth")
        self.gridLayout_3.addWidget(self.sbRoiWidth, 3, 1, 1, 1)
        self.verticalLayout_4.addWidget(self.groupBox_3)
        self.groupBox_5 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_5.setCheckable(False)
        self.groupBox_5.setObjectName("groupBox_5")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBox_5)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.leMinY = QtWidgets.QLineEdit(self.groupBox_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.leMinY.sizePolicy().hasHeightForWidth())
        self.leMinY.setSizePolicy(sizePolicy)
        self.leMinY.setMinimumSize(QtCore.QSize(0, 0))
        self.leMinY.setMaximumSize(QtCore.QSize(100, 16777215))
        self.leMinY.setAlignment(QtCore.Qt.AlignCenter)
        self.leMinY.setObjectName("leMinY")
        self.gridLayout_4.addWidget(self.leMinY, 2, 2, 1, 1)
        self.chbShowMax = QtWidgets.QCheckBox(self.groupBox_5)
        self.chbShowMax.setText("")
        self.chbShowMax.setObjectName("chbShowMax")
        self.gridLayout_4.addWidget(self.chbShowMax, 1, 4, 1, 1)
        self.leMinVal = QtWidgets.QLineEdit(self.groupBox_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.leMinVal.sizePolicy().hasHeightForWidth())
        self.leMinVal.setSizePolicy(sizePolicy)
        self.leMinVal.setMinimumSize(QtCore.QSize(0, 0))
        self.leMinVal.setMaximumSize(QtCore.QSize(100, 16777215))
        self.leMinVal.setAlignment(QtCore.Qt.AlignCenter)
        self.leMinVal.setObjectName("leMinVal")
        self.gridLayout_4.addWidget(self.leMinVal, 2, 3, 1, 1)
        self.leMaxVal = QtWidgets.QLineEdit(self.groupBox_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.leMaxVal.sizePolicy().hasHeightForWidth())
        self.leMaxVal.setSizePolicy(sizePolicy)
        self.leMaxVal.setMinimumSize(QtCore.QSize(0, 0))
        self.leMaxVal.setMaximumSize(QtCore.QSize(100, 16777215))
        self.leMaxVal.setAlignment(QtCore.Qt.AlignCenter)
        self.leMaxVal.setObjectName("leMaxVal")
        self.gridLayout_4.addWidget(self.leMaxVal, 1, 3, 1, 1)
        self.leMinX = QtWidgets.QLineEdit(self.groupBox_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.leMinX.sizePolicy().hasHeightForWidth())
        self.leMinX.setSizePolicy(sizePolicy)
        self.leMinX.setMinimumSize(QtCore.QSize(0, 0))
        self.leMinX.setMaximumSize(QtCore.QSize(100, 16777215))
        self.leMinX.setAlignment(QtCore.Qt.AlignCenter)
        self.leMinX.setObjectName("leMinX")
        self.gridLayout_4.addWidget(self.leMinX, 2, 1, 1, 1)
        self.chbShowMin = QtWidgets.QCheckBox(self.groupBox_5)
        self.chbShowMin.setText("")
        self.chbShowMin.setObjectName("chbShowMin")
        self.gridLayout_4.addWidget(self.chbShowMin, 2, 4, 1, 1)
        self.leComX = QtWidgets.QLineEdit(self.groupBox_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.leComX.sizePolicy().hasHeightForWidth())
        self.leComX.setSizePolicy(sizePolicy)
        self.leComX.setMinimumSize(QtCore.QSize(0, 0))
        self.leComX.setMaximumSize(QtCore.QSize(100, 16777215))
        self.leComX.setAlignment(QtCore.Qt.AlignCenter)
        self.leComX.setObjectName("leComX")
        self.gridLayout_4.addWidget(self.leComX, 3, 1, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.groupBox_5)
        self.label_15.setObjectName("label_15")
        self.gridLayout_4.addWidget(self.label_15, 3, 0, 1, 1)
        self.leComY = QtWidgets.QLineEdit(self.groupBox_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.leComY.sizePolicy().hasHeightForWidth())
        self.leComY.setSizePolicy(sizePolicy)
        self.leComY.setMinimumSize(QtCore.QSize(0, 0))
        self.leComY.setMaximumSize(QtCore.QSize(100, 16777215))
        self.leComY.setAlignment(QtCore.Qt.AlignCenter)
        self.leComY.setObjectName("leComY")
        self.gridLayout_4.addWidget(self.leComY, 3, 2, 1, 1)
        self.leComVal = QtWidgets.QLineEdit(self.groupBox_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.leComVal.sizePolicy().hasHeightForWidth())
        self.leComVal.setSizePolicy(sizePolicy)
        self.leComVal.setMinimumSize(QtCore.QSize(0, 0))
        self.leComVal.setMaximumSize(QtCore.QSize(100, 16777215))
        self.leComVal.setAlignment(QtCore.Qt.AlignCenter)
        self.leComVal.setObjectName("leComVal")
        self.gridLayout_4.addWidget(self.leComVal, 3, 3, 1, 1)
        self.chbShowCom = QtWidgets.QCheckBox(self.groupBox_5)
        self.chbShowCom.setText("")
        self.chbShowCom.setObjectName("chbShowCom")
        self.gridLayout_4.addWidget(self.chbShowCom, 3, 4, 1, 1)
        self.leFwhmX = QtWidgets.QLineEdit(self.groupBox_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.leFwhmX.sizePolicy().hasHeightForWidth())
        self.leFwhmX.setSizePolicy(sizePolicy)
        self.leFwhmX.setMinimumSize(QtCore.QSize(0, 0))
        self.leFwhmX.setMaximumSize(QtCore.QSize(100, 16777215))
        self.leFwhmX.setAlignment(QtCore.Qt.AlignCenter)
        self.leFwhmX.setObjectName("leFwhmX")
        self.gridLayout_4.addWidget(self.leFwhmX, 4, 1, 1, 1)
        self.leSum = QtWidgets.QLineEdit(self.groupBox_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.leSum.sizePolicy().hasHeightForWidth())
        self.leSum.setSizePolicy(sizePolicy)
        self.leSum.setMinimumSize(QtCore.QSize(0, 0))
        self.leSum.setMaximumSize(QtCore.QSize(100, 16777215))
        self.leSum.setAlignment(QtCore.Qt.AlignCenter)
        self.leSum.setObjectName("leSum")
        self.gridLayout_4.addWidget(self.leSum, 6, 1, 1, 1)
        self.sbThreshold = QtWidgets.QDoubleSpinBox(self.groupBox_5)
        self.sbThreshold.setMaximumSize(QtCore.QSize(110, 16777215))
        self.sbThreshold.setMaximum(99999999.0)
        self.sbThreshold.setObjectName("sbThreshold")
        self.gridLayout_4.addWidget(self.sbThreshold, 8, 1, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.groupBox_5)
        self.label_16.setObjectName("label_16")
        self.gridLayout_4.addWidget(self.label_16, 4, 0, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.groupBox_5)
        self.label_17.setObjectName("label_17")
        self.gridLayout_4.addWidget(self.label_17, 6, 0, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.groupBox_5)
        self.label_18.setObjectName("label_18")
        self.gridLayout_4.addWidget(self.label_18, 8, 0, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.groupBox_5)
        self.label_14.setObjectName("label_14")
        self.gridLayout_4.addWidget(self.label_14, 2, 0, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.groupBox_5)
        self.label_13.setObjectName("label_13")
        self.gridLayout_4.addWidget(self.label_13, 1, 0, 1, 1)
        self.leMaxX = QtWidgets.QLineEdit(self.groupBox_5)
        self.leMaxX.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.leMaxX.sizePolicy().hasHeightForWidth())
        self.leMaxX.setSizePolicy(sizePolicy)
        self.leMaxX.setMinimumSize(QtCore.QSize(0, 0))
        self.leMaxX.setMaximumSize(QtCore.QSize(100, 16777215))
        self.leMaxX.setAlignment(QtCore.Qt.AlignCenter)
        self.leMaxX.setObjectName("leMaxX")
        self.gridLayout_4.addWidget(self.leMaxX, 1, 1, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.groupBox_5)
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.gridLayout_4.addWidget(self.label_10, 0, 1, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.groupBox_5)
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.gridLayout_4.addWidget(self.label_11, 0, 2, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.groupBox_5)
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.gridLayout_4.addWidget(self.label_12, 0, 3, 1, 1)
        self.leMaxY = QtWidgets.QLineEdit(self.groupBox_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.leMaxY.sizePolicy().hasHeightForWidth())
        self.leMaxY.setSizePolicy(sizePolicy)
        self.leMaxY.setMinimumSize(QtCore.QSize(0, 0))
        self.leMaxY.setMaximumSize(QtCore.QSize(100, 16777215))
        self.leMaxY.setAlignment(QtCore.Qt.AlignCenter)
        self.leMaxY.setObjectName("leMaxY")
        self.gridLayout_4.addWidget(self.leMaxY, 1, 2, 1, 1)
        self.leFwhmY = QtWidgets.QLineEdit(self.groupBox_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.leFwhmY.sizePolicy().hasHeightForWidth())
        self.leFwhmY.setSizePolicy(sizePolicy)
        self.leFwhmY.setMinimumSize(QtCore.QSize(0, 0))
        self.leFwhmY.setMaximumSize(QtCore.QSize(100, 16777215))
        self.leFwhmY.setAlignment(QtCore.Qt.AlignCenter)
        self.leFwhmY.setObjectName("leFwhmY")
        self.gridLayout_4.addWidget(self.leFwhmY, 4, 2, 1, 1)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem11, 4, 3, 1, 1)
        self.label_21 = QtWidgets.QLabel(self.groupBox_5)
        self.label_21.setObjectName("label_21")
        self.gridLayout_4.addWidget(self.label_21, 0, 4, 1, 1)
        self.verticalLayout_4.addWidget(self.groupBox_5)
        spacerItem12 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem12)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.tab_3)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.chk_peak_search = QtWidgets.QCheckBox(self.tab_3)
        self.chk_peak_search.setObjectName("chk_peak_search")
        self.horizontalLayout_8.addWidget(self.chk_peak_search)
        spacerItem13 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem13)
        self.verticalLayout_6.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.rb_abs_threshold = QtWidgets.QRadioButton(self.tab_3)
        self.rb_abs_threshold.setChecked(True)
        self.rb_abs_threshold.setObjectName("rb_abs_threshold")
        self.bg_threshold = QtWidgets.QButtonGroup(SettingsWidget)
        self.bg_threshold.setObjectName("bg_threshold")
        self.bg_threshold.addButton(self.rb_abs_threshold)
        self.horizontalLayout_10.addWidget(self.rb_abs_threshold)
        self.sl_abs_threshold = QtWidgets.QSlider(self.tab_3)
        self.sl_abs_threshold.setMinimum(1)
        self.sl_abs_threshold.setMaximum(16000)
        self.sl_abs_threshold.setSingleStep(1000)
        self.sl_abs_threshold.setOrientation(QtCore.Qt.Horizontal)
        self.sl_abs_threshold.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.sl_abs_threshold.setTickInterval(500)
        self.sl_abs_threshold.setObjectName("sl_abs_threshold")
        self.horizontalLayout_10.addWidget(self.sl_abs_threshold)
        self.sb_abs_threshold = QtWidgets.QSpinBox(self.tab_3)
        self.sb_abs_threshold.setMinimum(1)
        self.sb_abs_threshold.setMaximum(16000)
        self.sb_abs_threshold.setSingleStep(1000)
        self.sb_abs_threshold.setObjectName("sb_abs_threshold")
        self.horizontalLayout_10.addWidget(self.sb_abs_threshold)
        self.verticalLayout_6.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.rb_rel_threshold = QtWidgets.QRadioButton(self.tab_3)
        self.rb_rel_threshold.setChecked(False)
        self.rb_rel_threshold.setObjectName("rb_rel_threshold")
        self.bg_threshold.addButton(self.rb_rel_threshold)
        self.horizontalLayout_7.addWidget(self.rb_rel_threshold)
        self.sl_rel_threshold = QtWidgets.QSlider(self.tab_3)
        self.sl_rel_threshold.setEnabled(False)
        self.sl_rel_threshold.setMinimum(1)
        self.sl_rel_threshold.setSingleStep(10)
        self.sl_rel_threshold.setOrientation(QtCore.Qt.Horizontal)
        self.sl_rel_threshold.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.sl_rel_threshold.setTickInterval(10)
        self.sl_rel_threshold.setObjectName("sl_rel_threshold")
        self.horizontalLayout_7.addWidget(self.sl_rel_threshold)
        self.sb_rel_threshold = QtWidgets.QSpinBox(self.tab_3)
        self.sb_rel_threshold.setEnabled(False)
        self.sb_rel_threshold.setMinimum(1)
        self.sb_rel_threshold.setSingleStep(10)
        self.sb_rel_threshold.setObjectName("sb_rel_threshold")
        self.horizontalLayout_7.addWidget(self.sb_rel_threshold)
        self.verticalLayout_6.addLayout(self.horizontalLayout_7)
        spacerItem14 = QtWidgets.QSpacerItem(20, 488, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem14)
        self.tabWidget.addTab(self.tab_3, "")
        self.verticalLayout.addWidget(self.tabWidget)
        spacerItem15 = QtWidgets.QSpacerItem(20, 126, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem15)

        self.retranslateUi(SettingsWidget)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(SettingsWidget)

    def retranslateUi(self, SettingsWidget):
        _translate = QtCore.QCoreApplication.translate
        SettingsWidget.setWindowTitle(_translate("SettingsWidget", "Form"))
        self.groupBox.setTitle(_translate("SettingsWidget", "Image settings"))
        self.label_26.setText(_translate("SettingsWidget", "Source:"))
        self.label_23.setText(_translate("SettingsWidget", "Folder to monitor:"))
        self.label.setText(_translate("SettingsWidget", "Exposure:"))
        self.label_3.setText(_translate("SettingsWidget", "Gain:"))
        self.label_22.setText(_translate("SettingsWidget", "Cut image:"))
        self.label_19.setText(_translate("SettingsWidget", "X:"))
        self.label_28.setText(_translate("SettingsWidget", "H:"))
        self.label_20.setText(_translate("SettingsWidget", "Y:"))
        self.label_27.setText(_translate("SettingsWidget", "W:"))
        self.lbFps_2.setText(_translate("SettingsWidget", "Reduce resolution"))
        self.lbFps_3.setText(_translate("SettingsWidget", "times"))
        self.lbFps.setText(_translate("SettingsWidget", "Limit FPS"))
        self.chk_dark_image.setText(_translate("SettingsWidget", "Substract dark image"))
        self.but_acq_dark_image.setText(_translate("SettingsWidget", "Acquire Dark Image"))
        self.but_load_dark_image.setText(_translate("SettingsWidget", "Load Dark Image"))
        self.but_save_dark_image.setText(_translate("SettingsWidget", "Save Dark Image"))
        self.tbAllParams.setText(_translate("SettingsWidget", "Open ATK panel"))
        self.groupBox_4.setTitle(_translate("SettingsWidget", "Levels"))
        self.chkAutoLevels.setText(_translate("SettingsWidget", "Auto Levels"))
        self.label_2.setText(_translate("SettingsWidget", "Min:"))
        self.label_4.setText(_translate("SettingsWidget", "Max:"))
        self.label_5.setText(_translate("SettingsWidget", "Color map:"))
        self.cbColorMap.setItemText(0, _translate("SettingsWidget", "Grey"))
        self.cbColorMap.setItemText(1, _translate("SettingsWidget", "Thermal"))
        self.cbColorMap.setItemText(2, _translate("SettingsWidget", "Flame"))
        self.cbColorMap.setItemText(3, _translate("SettingsWidget", "Yellowy"))
        self.cbColorMap.setItemText(4, _translate("SettingsWidget", "Bipolar"))
        self.cbColorMap.setItemText(5, _translate("SettingsWidget", "Spectrum"))
        self.cbColorMap.setItemText(6, _translate("SettingsWidget", "Cyclic"))
        self.cbColorMap.setItemText(7, _translate("SettingsWidget", "Qreyclip"))
        self.rb_lin_level.setText(_translate("SettingsWidget", "Lin"))
        self.rb_log_level.setText(_translate("SettingsWidget", "Log"))
        self.rb_sqrt_level.setText(_translate("SettingsWidget", "Sqrt"))
        self.gb_screen_motor.setTitle(_translate("SettingsWidget", "Screen control"))
        self.lb_screen_status.setText(_translate("SettingsWidget", "Screen In"))
        self.pbInOut.setText(_translate("SettingsWidget", "Move In"))
        self.chk_auto_screen.setText(_translate("SettingsWidget", "Enable auto screen"))
        self.gb_sardana.setTitle(_translate("SettingsWidget", "Sardana \"counter\" behavior"))
        self.lb_screen_status_2.setText(_translate("SettingsWidget", "Statistics value as counter:"))
        self.cb_counter.setItemText(0, _translate("SettingsWidget", "sum"))
        self.cb_counter.setItemText(1, _translate("SettingsWidget", "max_i"))
        self.cb_counter.setItemText(2, _translate("SettingsWidget", "max_x"))
        self.cb_counter.setItemText(3, _translate("SettingsWidget", "max_y"))
        self.cb_counter.setItemText(4, _translate("SettingsWidget", "com_x"))
        self.cb_counter.setItemText(5, _translate("SettingsWidget", "com_y"))
        self.cb_counter.setItemText(6, _translate("SettingsWidget", "fwhm_x"))
        self.cb_counter.setItemText(7, _translate("SettingsWidget", "fwhm_y"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("SettingsWidget", "Camera settings"))
        self.groupBox_2.setTitle(_translate("SettingsWidget", "Markers"))
        self.but_add_marker.setText(_translate("SettingsWidget", "Add Marker"))
        self.groupBox_3.setTitle(_translate("SettingsWidget", "ROI"))
        self.label_6.setText(_translate("SettingsWidget", "X:"))
        self.chbShowRoi.setText(_translate("SettingsWidget", "Enable"))
        self.label_8.setText(_translate("SettingsWidget", "H:"))
        self.label_9.setText(_translate("SettingsWidget", "W:"))
        self.label_7.setText(_translate("SettingsWidget", "Y:"))
        self.groupBox_5.setTitle(_translate("SettingsWidget", "Statistics"))
        self.label_15.setText(_translate("SettingsWidget", "CoM"))
        self.label_16.setText(_translate("SettingsWidget", "FWHM"))
        self.label_17.setText(_translate("SettingsWidget", "Sum"))
        self.label_18.setText(_translate("SettingsWidget", "BG"))
        self.label_14.setText(_translate("SettingsWidget", "Min"))
        self.label_13.setText(_translate("SettingsWidget", "Max"))
        self.label_10.setText(_translate("SettingsWidget", "X"))
        self.label_11.setText(_translate("SettingsWidget", "Y"))
        self.label_12.setText(_translate("SettingsWidget", "Value"))
        self.label_21.setText(_translate("SettingsWidget", "Mark"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("SettingsWidget", "ROI settings"))
        self.chk_peak_search.setText(_translate("SettingsWidget", "Enable peak search"))
        self.rb_abs_threshold.setText(_translate("SettingsWidget", "Absolute threshold"))
        self.rb_rel_threshold.setText(_translate("SettingsWidget", "Relative thershold"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("SettingsWidget", "Peak search"))
